const PAKISTAN_CITIES = [
  // ── Islamabad ──
  "Islamabad",

  // ── Punjab ──
  "Lahore",
  "Faisalabad",
  "Rawalpindi",
  "Gujranwala",
  "Multan",
  "Bahawalpur",
  "Sargodha",
  "Sialkot",
  "Sheikhupura",
  "Rahim Yar Khan",
  "Jhang",
  "Dera Ghazi Khan",
  "Gujrat",
  "Sahiwal",
  "Wah Cantonment",
  "Kasur",
  "Okara",
  "Chiniot",
  "Kamoke",
  "Hafizabad",
  "Khanewal",
  "Muzaffargarh",
  "Mandi Bahauddin",
  "Jhelum",
  "Khanpur",
  "Pakpattan",
  "Daska",
  "Gojra",
  "Muridke",
  "Bahawalnagar",
  "Samundri",
  "Toba Tek Singh",
  "Vehari",
  "Chishtian",
  "Attock",
  "Layyah",
  "Mianwali",
  "Burewala",
  "Hasilpur",
  "Arifwala",
  "Kot Addu",
  "Shakargarh",
  "Renala Khurd",
  "Narowal",
  "Chakwal",
  "Khushab",
  "Mailsi",
  "Rajanpur",
  "Lodhran",
  "Jaranwala",
  "Ahmedpur East",
  "Talagang",
  "Taunsa",
  "Pattoki",
  "Dunya Pur",
  "Minchinabad",
  "Kabirwala",
  "Kunri",
  "Phalia",
  "Pir Mahal",
  "Lalamusa",
  "Dina",
  "Kallar Kahar",
  "Bhalwal",
  "Sangla Hill",
  "Shorkot",
  "Sillanwali",
  "Wazirabad",

  // ── Sindh ──
  "Karachi",
  "Hyderabad",
  "Sukkur",
  "Larkana",
  "Nawabshah",
  "Mirpur Khas",
  "Jacobabad",
  "Shikarpur",
  "Khairpur",
  "Dadu",
  "Tando Allahyar",
  "Badin",
  "Thatta",
  "Kotri",
  "Ghotki",
  "Tando Muhammad Khan",
  "Umerkot",
  "Kashmore",
  "Kandhkot",
  "Rohri",
  "Matiari",
  "Sanghar",
  "Naushahro Feroze",
  "Moro",
  "Sakrand",
  "Sehwan",
  "Mehar",
  "Hala",
  "Jamshoro",
  "Kamber Ali Khan",
  "Daharki",
  "Ratodero",
  "Ranipur",
  "Dokri",
  "Nasirabad",

  // ── Khyber Pakhtunkhwa ──
  "Peshawar",
  "Mardan",
  "Abbottabad",
  "Swat (Mingora)",
  "Kohat",
  "Bannu",
  "Dera Ismail Khan",
  "Charsadda",
  "Mansehra",
  "Nowshera",
  "Haripur",
  "Chitral",
  "Swabi",
  "Batagram",
  "Karak",
  "Hangu",
  "Timergara",
  "Parachinar",
  "Tank",
  "Lakki Marwat",
  "Shangla",
  "Buner",
  "Mohmand",
  "Khyber",
  "Kurram",
  "Orakzai",
  "North Waziristan",
  "South Waziristan",

  // ── Balochistan ──
  "Quetta",
  "Turbat",
  "Khuzdar",
  "Chaman",
  "Hub",
  "Gwadar",
  "Dera Murad Jamali",
  "Zhob",
  "Loralai",
  "Sibi",
  "Ziarat",
  "Panjgur",
  "Nushki",
  "Pasni",
  "Jiwani",
  "Dalbandin",
  "Mastung",
  "Kalat",
  "Kharan",
  "Usta Muhammad",
  "Sohbatpur",
  "Duki",
  "Kohlu",
  "Barkhan",
  "Musakhel",
  "Qila Saifullah",
  "Qila Abdullah",
  "Washuk",
  "Awaran",
  "Lasbela",
  "Sherani",
  "Harnai",

  // ── Gilgit-Baltistan ──
  "Gilgit",
  "Skardu",
  "Hunza (Karimabad)",
  "Ghizer",
  "Astore",
  "Khaplu",
  "Shigar",
  "Nagar",
  "Ghanche",
  "Diamer (Chilas)",
  "Tangir",

  // ── Azad Jammu & Kashmir ──
  "Muzaffarabad",
  "Mirpur",
  "Rawalakot",
  "Kotli",
  "Bhimber",
  "Palandri",
  "Hajira",
  "Bagh",
  "Hattian Bala",
  "Neelum (Athmuqam)",
].sort((a, b) => a.localeCompare(b));

export default PAKISTAN_CITIES;
